webtalk_init -webtalk_dir C:/Users/salty/Minhaj/Habib University/Semester - 4/Computer Architecture/Computer_Architecture_Final_Project/Task1/Single Cycle Processor.sim/sim_1/behav/xsim/xsim.dir/tb_MainProcessor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 21 09:53:29 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "08b81001-8833-4bf4-a64e-014f48b08d7f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "08f1fc4cc3bc4a108f7662e8d5bc6a34" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "39" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Celeron(R) N4020 CPU @ 1.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1094 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7668_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1599458414 -regid "" -xml C:/Users/salty/Minhaj/Habib University/Semester - 4/Computer Architecture/Computer_Architecture_Final_Project/Task1/Single Cycle Processor.sim/sim_1/behav/xsim/xsim.dir/tb_MainProcessor_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/salty/Minhaj/Habib University/Semester - 4/Computer Architecture/Computer_Architecture_Final_Project/Task1/Single Cycle Processor.sim/sim_1/behav/xsim/xsim.dir/tb_MainProcessor_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/salty/Minhaj/Habib University/Semester - 4/Computer Architecture/Computer_Architecture_Final_Project/Task1/Single Cycle Processor.sim/sim_1/behav/xsim/xsim.dir/tb_MainProcessor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
